# Generated by Django 3.2.16 on 2023-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_telegramanalysis_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='conclusion',
            new_name='Technology',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='channel_name',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='overall_report',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='promotion',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='video_report',
            new_name='hobby',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='about_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='comments_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='description_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='transcript_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='video_url',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='projects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='questionnaire_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
