# Generated by Django 3.2.16 on 2023-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20230904_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='recommendations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
