# Generated by Django 3.2.16 on 2023-09-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_analysisresult_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramanalysis',
            old_name='channel_report',
            new_name='Technology',
        ),
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='channel_score',
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='general_report',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='hobby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='overall_report',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='personality_report',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='projects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='questionnaire_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='recommendations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
